### ISSUE TITLE
Error: clone failed: can't lock file '/var/lock/pve-manager/pve-storage-data-zfs' - got timeout

### ISSUE THREAD

**Issue by owlfog** [khanh-ph/proxmox-kubernetes#71]
Hi @khanh-ph thanks for your awesome solution!
you did a great job!

i got this error:
`│ Error: clone failed: can't lock file '/var/lock/pve-manager/pve-storage-data-zfs' - got timeout
│ 
│   with module.k8s_prometheus_nodes.proxmox_vm_qemu.ubuntu_vm[0],
│   on modules/proxmox_ubuntu_vm/main.tf line 12, in resource "proxmox_vm_qemu" "ubuntu_vm":
│   12: resource "proxmox_vm_qemu" "ubuntu_vm" {
`
it has to do with timeout https://github.com/Telmate/terraform-provider-proxmox/issues/431
for myself I added 2 parameters and it solved my problem:
pm_parallel         = "2"
pm_timeout          = "600"

maybe this will help someone too)

**Comment by khanh-ph** [comment]
Hello @owlfog,

Thank you so much for bringing this to my attention! It appears to be a known issue that arises when provisioning multiple VMs concurrently. Interestingly, I hadn't encountered this in my tests, especially when using just a few VMs with NVMe SSDs.

I'll definitely allocate some time to investigate and address this. Your feedback is invaluable, and I truly appreciate your contribution to improving this project.
