### ISSUE TITLE
Error: vm 'ubuntu-2404' not found

### ISSUE THREAD

**Issue by Dryymoon** [khanh-ph/proxmox-kubernetes#99]
Proxmox v.8.1.3

After run a commad:
`terraform apply -var-file="example.tfvars" -auto-approve`
Got an issue:

`
module.k8s_control_plane_nodes.proxmox_vm_qemu.ubuntu_vm[0]: Creating...
module.k8s_worker_nodes.proxmox_vm_qemu.ubuntu_vm[1]: Creating...
module.kubespray_host.proxmox_vm_qemu.ubuntu_vm[0]: Creating...
module.k8s_worker_nodes.proxmox_vm_qemu.ubuntu_vm[0]: Creating...
module.k8s_worker_nodes.proxmox_vm_qemu.ubuntu_vm[2]: Creating...
╷
│ Error: vm 'ubuntu-2404' not found
│ 
│   with module.k8s_worker_nodes.proxmox_vm_qemu.ubuntu_vm[2],
│   on modules/proxmox_ubuntu_vm/main.tf line 12, in resource "proxmox_vm_qemu" "ubuntu_vm":
│   12: resource "proxmox_vm_qemu" "ubuntu_vm" {
│ 
╵
╷
│ Error: vm 'ubuntu-2404' not found
│ 
│   with module.kubespray_host.proxmox_vm_qemu.ubuntu_vm[0],
│   on modules/proxmox_ubuntu_vm/main.tf line 12, in resource "proxmox_vm_qemu" "ubuntu_vm":
│   12: resource "proxmox_vm_qemu" "ubuntu_vm" {
│ 
╵
╷
│ Error: vm 'ubuntu-2404' not found
│ 
│   with module.k8s_control_plane_nodes.proxmox_vm_qemu.ubuntu_vm[0],
│   on modules/proxmox_ubuntu_vm/main.tf line 12, in resource "proxmox_vm_qemu" "ubuntu_vm":
│   12: resource "proxmox_vm_qemu" "ubuntu_vm" {
│ 
╵
╷
│ Error: vm 'ubuntu-2404' not found
│ 
│   with module.k8s_worker_nodes.proxmox_vm_qemu.ubuntu_vm[1],
│   on modules/proxmox_ubuntu_vm/main.tf line 12, in resource "proxmox_vm_qemu" "ubuntu_vm":
│   12: resource "proxmox_vm_qemu" "ubuntu_vm" {
│ 
╵
╷
│ Error: vm 'ubuntu-2404' not found
│ 
│   with module.k8s_worker_nodes.proxmox_vm_qemu.ubuntu_vm[0],
│   on modules/proxmox_ubuntu_vm/main.tf line 12, in resource "proxmox_vm_qemu" "ubuntu_vm":
│   12: resource "proxmox_vm_qemu" "ubuntu_vm" {
│ 
╵

`

**Comment by ihsanovali** [comment]
I think you should create a template. Can do with: https://github.com/khanh-ph/proxmox-scripts/tree/master/create-vm-template
Also you can follow: https://www.khanhph.com/install-proxmox-kubernetes/

**Comment by Dryymoon** [comment]
It works, thanks for a quick reply
